apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: cogeex:matching-service-latest
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "test"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql-db:5432/cogeex_v2_database"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: cogeex-matching-service
spec:
  type: ClusterIP
  selector:
    app: matching-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
