apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  labels:
    app: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
      - name: project-service
        image: cogeex:project-service-latest
        ports:
        - containerPort: 9091
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "test"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql-db:5432/cogeex_v2_database"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: cogeex-project-service
spec:
  type: ClusterIP
  selector:
    app: project-service
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
