apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: auth-service
        image: ousshen/cogeex:auth-service-latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "test"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql-db:5432/cogeex_v2_database"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: cogeex-auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
